### ISSUE TITLE
Error when enabling "wallpattern dividers enabled"

### ISSUE THREAD

**Issue by thepauly** [ostat/gridfinity_extended_openscad#208]
I'm getting this error in OpenSCAD and a similar one in the Makerworld customizer when trying to enable a wallpattern pattern on dividers.

ERROR: Assertion '(is_num(canvasSize.x) && (canvasSize.x > 0))' failed: "canvasSize.x must be a positive number" in file modules/module_patterns.scad, line 329

<img width="1624" height="1056" alt="Image" src="https://github.com/user-attachments/assets/d59404bb-17dc-449f-b8e4-5a8b40ebf61c" />

**Comment by ostat** [comment]
I think this is fixed now. Not uploaded to Makerworld yet, just GitHub.

**Comment by mrene** [comment]
I still get the error with `gridfinity_basic_cup` using 5f458b197dd6f7ad344cf1892ef855cef003cf75

**Comment by ostat** [comment]
I see, try now?

**Comment by thepauly** [comment]
Thanks so much.

Error has gone but there is no pattern on the dividers.

<img width="860" height="662" alt="Image" src="https://github.com/user-attachments/assets/e5e8adf1-bc9d-45a4-ab1b-bcbf98b091e1" />

**Comment by ostat** [comment]
You can turn off `wallpattern coloured` to fix that. I will correct that logic.

**Comment by ostat** [comment]
This has been fixed.
